Add Minesweeper example application
JetBrains/compose-jb pull request #1500
Opened 2021-11-29 10:40 UTC by VeselovAlex

2021-11-29 12:43 UTC, olonho commented on examples/minesweeper/README.md
> +A simple game powered by Jetpack Compose and Kotlin Multiplatform
Compose Multiplatform

2021-11-29 12:45 UTC, olonho commented on examples/minesweeper/settings.gradle.kts
> +pluginManagement {
Maybe no longer needed.

2021-11-29 14:25 UTC, olonho approved these changes

2021-11-29 21:00 UTC, olonho requested changes
Please migrate to 1.0.0-rc6 and get rid of warnings.

2021-11-30 16:27 UTC, olonho approved these changes

2021-12-08 15:17 UTC, igordmn commented on examples/minesweeper/build.gradle.kts
> +    id("org.jetbrains.compose") version "1.0.0-rc6"
- use 1.0.0
- migrate to new template:
https://github.com/JetBrains/compose-jb/commit/dbd0a21949633302fcf98ad79c78896bbc6250ba#diff-7d46308093aec3efc8dd6079383a7b856efa79af87787a1fb2898504e0c4d027
![image](https://user-images.githubusercontent.com/5963351/145233475-73f13498-9083-4701-a61a-8e4d98d46a49.png)
-  add this example to https://github.com/JetBrains/compose-jb/blob/master/examples/validateExamples.sh

2022-01-19 14:26 UTC, olonho commented
Looks good, but not yet native targets ready.

2022-01-20 10:39 UTC, merged