Fix jnilib files not signed
JetBrains/compose-jb pull request #1799
Opened 2022-02-06 20:41 UTC by Thomas-Vos

You can see here that only `dylib` files are signed:

https://github.com/openjdk/jdk/blob/f7814c120bf84d7e9b459f81a6ce19b44fa122ec/src/jdk.jpackage/macosx/classes/jdk/jpackage/internal/MacAppImageBuilder.java#L673-L677

So that means that `jnilib` files still need to be signed manually.

2022-02-07 23:18 UTC, Thomas-Vos commented
Without the PR you get the following:
<img width="788" alt="Screenshot 2022-02-08 at 00 17 19" src="https://user-images.githubusercontent.com/11077217/152888447-c3998b2e-005d-460c-a9fd-c57eec58b251.png">

These libs were added using `fromFiles` in Gradle compose configuration.

2022-02-08 07:39 UTC, AlexeyTsvetkov commented
I don't think the fix works ATM, because `jnilib` extension is checked, after a file is determined to have a `dylib` extension:
```
if (source.name.isDylibPath) {
    // ...
            if (source.name.endsWith(".jnilib")) {
                signer.sign(target)
            } else {
                signer.unsign(target)
            }
        }
        else -> {
            if (source.name.endsWith(".jnilib")) {
                signer.sign(target)
            }
        }
    // ...
}
```

Overall, the idea looks good to me, but I would prefer something like:
```
if (source.name.isDylibPath) {
     // ... same as before
} else if (source.name.isJnilibPath) {
    signer.sign(target)
}
```

2022-02-08 07:40 UTC, AlexeyTsvetkov requested changes
I don't think the fix works ATM, because `jnilib` extension is checked, after a file is determined to have a `dylib` extension:
```
if (source.name.isDylibPath) {
    // ...
            if (source.name.endsWith(".jnilib")) {
                signer.sign(target)
            } else {
                signer.unsign(target)
            }
        }
        else -> {
            if (source.name.endsWith(".jnilib")) {
                signer.sign(target)
            }
        }
    // ...
}
```

Overall, the idea looks good to me, but I would prefer something like:
```
if (source.name.isDylibPath) {
     // ... same as before
} else if (source.name.isJnilibPath) {
    signer.sign(target)
}
```

2022-02-08 10:33 UTC, Thomas-Vos commented
@AlexeyTsvetkov actually the fix does work, because the `isDylibPath` function (which already existed), checks for both extensions. See:

https://github.com/JetBrains/compose-jb/blob/a1c4c8a41ee37c2f56ced2598ffb124decc28c6d/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/files/MacJarSignFileCopyingProcessor.kt#L76-L77

However, I can change it because I agree that it is not that clear.

2022-02-08 12:42 UTC, AlexeyTsvetkov commented
@Thomas-Vos whoops, my bad :) LGTM

2022-02-08 12:43 UTC, AlexeyTsvetkov approved these changes

2022-02-08 12:43 UTC, merged